// AUTO-GENERATED by MythOS - Mylo inline-edit bridge (preview only).
(function () {
  if (typeof window === "undefined") return;
  if (window.__myloEditInit) return;
  window.__myloEditInit = true;

  var enabled = false;      // text/image edit mode
  var selectMode = false;   // section-select mode
  var editingEl = null;
  var originalText = "";
  var pendingColor = null;
  var colorBar = null;
  var hoverBox = null;
  var selectedSection = null;
  var SKIP = { SCRIPT: 1, STYLE: 1, IMG: 1, SVG: 1, PATH: 1, INPUT: 1, TEXTAREA: 1, SELECT: 1, BUTTON: 1, VIDEO: 1, IFRAME: 1, CODE: 1, PRE: 1 };
  var SECTION_TAGS = { SECTION: 1, HEADER: 1, FOOTER: 1, ARTICLE: 1, ASIDE: 1, NAV: 1, MAIN: 1 };
  var COLORS = ["#111827", "#ffffff", "#6b7280", "#ef4444", "#f97316", "#f59e0b", "#eab308", "#22c55e", "#14b8a6", "#3b82f6", "#6366f1", "#a855f7", "#ec4899"];

  function post(msg) {
    msg.source = "mylo-edit";
    try { window.parent.postMessage(msg, "*"); } catch (e) {}
  }
  function box(r) {
    return { top: r.top, left: r.left, width: r.width, height: r.height };
  }

  function isEditableTextEl(el) {
    if (!el || el.nodeType !== 1) return false;
    if (SKIP[el.tagName]) return false;
    for (var i = 0; i < el.childNodes.length; i++) {
      var n = el.childNodes[i];
      if (n.nodeType === 3 && n.nodeValue && n.nodeValue.trim()) return true;
    }
    return false;
  }

  // ---- clicks ------------------------------------------------------------
  function onClick(e) {
    if (selectMode) { onSelectClick(e); return; }
    if (!enabled) return;
    var el = e.target;
    // Image swap: clicking an <img> (or inside one) offers to change the picture.
    var img = el.tagName === "IMG" ? el : (el.closest ? el.closest("img") : null);
    if (img) {
      e.preventDefault();
      e.stopPropagation();
      var r = img.getBoundingClientRect();
      post({ type: "image-clicked", src: img.getAttribute("src") || img.src || "", alt: img.getAttribute("alt") || "", rect: box(r) });
      return;
    }
    if (!isEditableTextEl(el)) return;
    e.preventDefault();
    e.stopPropagation();
    startEdit(el, e.clientX, e.clientY);
  }

  function caretFromPoint(x, y) {
    if (document.caretRangeFromPoint) return document.caretRangeFromPoint(x, y);
    if (document.caretPositionFromPoint) {
      var pos = document.caretPositionFromPoint(x, y);
      if (pos) {
        var r = document.createRange();
        r.setStart(pos.offsetNode, pos.offset);
        r.collapse(true);
        return r;
      }
    }
    return null;
  }

  // ---- text edit + color -------------------------------------------------
  function startEdit(el, x, y) {
    if (editingEl && editingEl !== el) finishEdit();
    editingEl = el;
    originalText = el.textContent;
    pendingColor = null;
    el.setAttribute("contenteditable", "true");
    el.classList.add("mylo-editing");
    el.focus();
    try {
      var range = caretFromPoint(x, y);
      if (range) {
        var sel = window.getSelection();
        sel.removeAllRanges();
        sel.addRange(range);
      }
    } catch (err) {}
    el.addEventListener("blur", finishEdit, { once: true });
    el.addEventListener("keydown", onKey);
    showColorBar(el);
  }

  function onKey(e) {
    if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); e.target.blur(); }
    else if (e.key === "Escape") { e.target.textContent = originalText; pendingColor = null; e.target.blur(); }
  }

  function showColorBar(el) {
    removeColorBar();
    var r = el.getBoundingClientRect();
    var bar = document.createElement("div");
    bar.id = "mylo-color-bar";
    bar.style.cssText =
      "position:fixed;z-index:2147483647;display:flex;gap:4px;padding:6px 8px;border-radius:10px;" +
      "background:#0e111a;box-shadow:0 8px 24px rgba(0,0,0,.35);align-items:center;" +
      "top:" + Math.max(8, r.top - 44) + "px;left:" + Math.max(8, r.left) + "px;";
    var label = document.createElement("span");
    label.textContent = "Color";
    label.style.cssText = "color:#9aa1ac;font:600 11px system-ui;margin-right:2px;";
    bar.appendChild(label);
    for (var i = 0; i < COLORS.length; i++) {
      (function (c) {
        var sw = document.createElement("button");
        sw.type = "button";
        sw.style.cssText =
          "width:18px;height:18px;border-radius:50%;border:1px solid rgba(255,255,255,.25);cursor:pointer;padding:0;background:" + c + ";";
        sw.addEventListener("mousedown", function (ev) { ev.preventDefault(); });
        sw.addEventListener("click", function (ev) { ev.preventDefault(); applyColor(c); });
        bar.appendChild(sw);
      })(COLORS[i]);
    }
    document.body.appendChild(bar);
    colorBar = bar;
  }
  function removeColorBar() {
    if (colorBar && colorBar.parentNode) colorBar.parentNode.removeChild(colorBar);
    colorBar = null;
  }
  function applyColor(color) {
    if (!editingEl) return;
    pendingColor = color;
    editingEl.style.color = color;
  }

  function finishEdit() {
    var el = editingEl;
    if (!el) return;
    editingEl = null;
    removeColorBar();
    el.removeEventListener("keydown", onKey);
    el.removeAttribute("contenteditable");
    el.classList.remove("mylo-editing");
    var newText = (el.textContent || "").replace(/\s+/g, " ").trim();
    var oldText = (originalText || "").replace(/\s+/g, " ").trim();
    if (oldText && (newText !== oldText || pendingColor)) {
      post({ type: "text-changed", oldText: oldText, newText: newText, color: pendingColor || null });
    }
    pendingColor = null;
  }

  // ---- section select ----------------------------------------------------
  function sectionFor(el) {
    var node = el;
    while (node && node.nodeType === 1 && node.tagName !== "BODY") {
      var parent = node.parentElement;
      if (SECTION_TAGS[node.tagName]) return node;
      if (parent && (parent.tagName === "BODY" || parent.tagName === "MAIN")) return node;
      node = parent;
    }
    return el && el.nodeType === 1 ? el : null;
  }
  function ensureHoverBox() {
    if (hoverBox) return hoverBox;
    var b = document.createElement("div");
    b.id = "mylo-hover-box";
    b.style.cssText = "position:fixed;z-index:2147483646;pointer-events:none;border:2px solid #6366f1;border-radius:8px;background:rgba(99,102,241,.08);transition:all .05s;display:none;";
    document.body.appendChild(b);
    hoverBox = b;
    return b;
  }
  function positionBox(b, el, solid) {
    var r = el.getBoundingClientRect();
    b.style.display = "block";
    b.style.top = r.top + "px";
    b.style.left = r.left + "px";
    b.style.width = r.width + "px";
    b.style.height = r.height + "px";
    b.style.borderStyle = solid ? "solid" : "dashed";
  }
  function onHover(e) {
    if (!selectMode) return;
    var sec = sectionFor(e.target);
    if (!sec) return;
    positionBox(ensureHoverBox(), sec, false);
  }
  function onSelectClick(e) {
    var sec = sectionFor(e.target);
    if (!sec) return;
    e.preventDefault();
    e.stopPropagation();
    selectedSection = sec;
    positionBox(ensureHoverBox(), sec, true);
    var heading = sec.querySelector ? sec.querySelector("h1,h2,h3,h4") : null;
    var label = (heading && heading.textContent ? heading.textContent : (sec.getAttribute && sec.getAttribute("id")) || sec.tagName).replace(/\s+/g, " ").trim().slice(0, 60);
    var text = (sec.innerText || sec.textContent || "").replace(/\s+/g, " ").trim().slice(0, 2000);
    var html = (sec.outerHTML || "").slice(0, 6000);
    post({ type: "section-selected", label: label, text: text, html: html });
  }

  // ---- mode toggles ------------------------------------------------------
  function setEnabled(on) {
    enabled = !!on;
    if (on) setSelectMode(false);
    document.documentElement.classList.toggle("mylo-edit-mode", enabled);
    if (!enabled && editingEl) finishEdit();
  }
  function setSelectMode(on) {
    selectMode = !!on;
    document.documentElement.classList.toggle("mylo-select-mode", selectMode);
    if (selectMode) {
      if (enabled) setEnabled(false);
      document.addEventListener("mousemove", onHover, true);
    } else {
      document.removeEventListener("mousemove", onHover, true);
      if (hoverBox) hoverBox.style.display = "none";
      selectedSection = null;
    }
  }

  function injectStyle() {
    if (document.getElementById("mylo-edit-style")) return;
    var s = document.createElement("style");
    s.id = "mylo-edit-style";
    s.textContent =
      ".mylo-edit-mode, .mylo-edit-mode * { cursor: text !important; }" +
      ".mylo-edit-mode img { cursor: pointer !important; }" +
      ".mylo-select-mode, .mylo-select-mode * { cursor: pointer !important; }" +
      ".mylo-editing { outline: 1px dashed #3b82f6 !important; outline-offset: 4px; background: transparent !important; border-radius: 2px; }";
    (document.head || document.documentElement).appendChild(s);
  }

  function ready(fn) {
    if (document.readyState !== "loading") fn();
    else document.addEventListener("DOMContentLoaded", fn);
  }

  document.addEventListener("click", onClick, true);
  window.addEventListener("message", function (e) {
    var d = e.data;
    if (!d || d.source !== "mylo") return;
    if (d.type === "edit-mode") setEnabled(d.enabled);
    else if (d.type === "select-mode") setSelectMode(d.enabled);
  });

  ready(function () {
    injectStyle();
    try { window.parent.postMessage({ source: "mylo-edit", type: "ready" }, "*"); } catch (err) {}
  });
})();
